install:
	pip install torch==2.5.1+cu118 --index-url https://download.pytorch.org/whl/cu118
	pip install torchvision==0.20.1+cu118 --index-url https://download.pytorch.org/whl/cu118
	pip install -e .
 